### ISSUE TITLE
Increase LO scale factor number of bits

### ISSUE THREAD

**Issue by sr-cdf** [realtimeradio/souk-firmware#21]
The scale factor is currently 8-bits, which gives quite coarse steps at low scales.

12-bit would be better, 16-bit is probably overkill.

**Comment by jack-h** [comment]
rev 5.5.3 uses 12 bits

**Comment by jack-h** [comment]
@sr-cdf I've just realised I probably did the wrong thing here -- Am I right in thinking you wanted 12 bits but with 4 fractional bits. I.e., keep the 1/256 maximum attenuation, but set the step size to

**Comment by sr-cdf** [comment]
Your message got cut off at the end but I think just 12 total bits going
down from 1 to 1 / 2**12 is fine. Do you mean there is an option to add
additional gain by adjusting the fixed point decimal place? I don't think
that's necessary.

**Comment by jack-h** [comment]
Ignore, I misunderstood how the gain factor was being applied :)
