### ISSUE TITLE
Change PFB window function

### ISSUE THREAD

**Issue by jack-h** [realtimeradio/souk-firmware#25]
@sr-cdf -- what window spec to you desire?

**Comment by sr-cdf** [comment]
try `scipy.signal.windows.dpss(window_len, NW=2.0)`
your plotting script shows it to be flatter in band with lower lobes than the hanning window:

![Screenshot_20230824_135258](https://github.com/realtimeradio/souk-firmware/assets/17500915/d1e8f106-806e-4312-96f2-79ea6fd008d6)

**Comment by jack-h** [comment]
Updated in `souk_single_pipeline_4x2_2023-08-30_1832.fpg`

**Comment by jack-h** [comment]
Nice -- I think there is certainly scope to improve the spur level a little
if necessary, either by slightly increasing the number of taps in the
filter and/or tweaking `NW` in the window generation function.
