### ISSUE TITLE
Tones at wrong frequencies 

### ISSUE THREAD

**Issue by sr-cdf** [realtimeradio/souk-firmware#28]
Sometimes, tones come out at the wrong frequencies.

Examples:

2048 tones at bin centers (600kHz spacing) works fine despite numerous `serial reorder clash` errors:
```
N_TX_FFT    = 2048 #per bank
bin_centers = np.fft.fftfreq(2*N_TX_FFT, 1./(2*MIXFREQ)) + MIXFREQ
bins        = np.arange(len(bin_centers))
freqs       = bin_centers[:2048]
```
![2048-tones-600khz](https://github.com/realtimeradio/souk-firmware/assets/17500915/e373dad4-eddc-4f3b-9aaf-4c515bc5ad6b)
  

But 2048 tones between 200MHz and 2250 MHz (~1MHz spacing) does not:
```
freqs       = np.linspace(200e6,2250e6,2048)
```
![2048-tones-1001khz](https://github.com/realtimeradio/souk-firmware/assets/17500915/9d303cd7-20c2-4d70-bf7e-c3ecfc9f5197)
  
  
  

16 tones at spacing slightly larger than the 600kHz works fine:
```
bins  = arange(16)
freqs = bin_centers[bins]*1.1
```
![16-tones-660khz](https://github.com/realtimeradio/souk-firmware/assets/17500915/2086ddce-271a-4042-8db1-a6515eccdc7f)

  

But adding one more tone to the end gives a single tone (the 9th) out of place with the following error:
```
In [179]: bins=arange(17)

In [180]: freqs=bin_centers[bins]*1.1; num=len(freqs)

In [181]: setfreqpsb(r,freqs[:num],phases[:num],amplitude=ones(num),fftshiftstages=None)
2023-09-19 14:37:55,544 - souk_mkid_readout.blocks.block:rfsoc4x2:p0_synth_input_reorder - ERROR - Serial reorder clash!
2023-09-19 14:37:55,544 - souk_mkid_readout.blocks.block:rfsoc4x2:p0_synth_input_reorder - INFO - Attempted: 111->16 Setting input (p:s) 0:2 to 7:13
2023-09-19 14:37:55,544 - souk_mkid_readout.blocks.block:rfsoc4x2:p0_synth_input_reorder - INFO - Previously: 107->8 Setting input (p:s) 0:1 to 3:13
Out[181]: 
array([1.35168e+09, 1.35234e+09, 1.35300e+09, 1.35366e+09, 1.35432e+09,
       1.35498e+09, 1.35564e+09, 1.35630e+09, 1.35696e+09, 1.35762e+09,
       1.35828e+09, 1.35894e+09, 1.35960e+09, 1.36026e+09, 1.36092e+09,
       1.36158e+09, 1.36224e+09])

```
![17-tones-660khz](https://github.com/realtimeradio/souk-firmware/assets/17500915/2641fa98-786f-4c00-aa22-1cecaeb2b667)

**Comment by jack-h** [comment]
@sr-cdf I believe this is fixed in v6, but please confirm at your leisure
