### ISSUE TITLE
relative path fail in config yaml

### ISSUE THREAD

**Issue by sr-cdf** [realtimeradio/souk-firmware#34]
Hey @jack-h ,
In `souk-firmware/software/control_sw/config/souk-single-pipeline-krm.yaml` there is a relative path which fails if you don;t start python from the appropriate level:
`fpgfile: ./../../../firmware/src/souk_single_pipeline_krm/outputs/souk_single_pipeline_krm.fpg`

Would be nice if it was absolute eg `fpgfile: /home/casper/src/souk-firmware/firmware/src/souk_single_pipeline_krm/outputs/souk_single_pipeline_krm.fpg`

**Comment by jack-h** [comment]
Fixed in v5.6. Now merged into v6 branch
