### ISSUE TITLE
ADC clock to 4Gsps

### ISSUE THREAD

**Issue by jack-h** [realtimeradio/souk-firmware#46]
@sr-cdf

Does the clock rate have to be exactly 4 Gsps (which would need a change of upstream PLL outputs) or is 4096 Msps workable?

**Comment by sr-cdf** [comment]
4096 is good, what is the next lowest available rate, out of interest?

**Comment by jack-h** [comment]
It seems to be steps of the reference clock (409.6M)

**Comment by jack-h** [comment]
Added 4.096 ADC clock version at https://github.com/realtimeradio/souk-firmware/commit/4093c3e47d90b9c2650bdacc1ce5e1f422c1dfad

**Comment by sr-cdf** [comment]
Sweet, thanks
